In [1]:
import numpy as np
np.__version__

'1.18.1'

In [13]:
a = np.array([1,2,3], dtype='int8')
print(a)

[1 2 3]


In [27]:
b = np.array([[2.0,3.0,5.0],[5.0,6.0,9.0]])
print(b)

[[2. 3. 5.]
 [5. 6. 9.]]


In [6]:
b.ndim

2

In [11]:
b.shape

(2, 3)

In [28]:
b.dtype

dtype('float64')

In [26]:
b.itemsize

8

In [32]:
# a.size * a.itemsize
a.nbytes

3

In [34]:
demo_array = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(demo_array)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [39]:
# demo_array[-1, -3]
demo_array[1, 5]

13

In [40]:
demo_array[1,:]

array([ 8,  9, 10, 11, 12, 13, 14])

In [41]:
demo_array[:,2]

array([ 3, 10])

In [43]:
demo_array[0,1:6:2]

array([2, 4, 6])